server:
  port: 8080

spring:
  application:
    name: k8s-demo
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
#      base-path: /application
  metrics:
    tags:
      application: ${spring.application.name} # prometheus label 에 추가됨