server:
  port: 8080

spring:
  application:
    name: prometheus-demo-server
management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
#      base-path: /application
  metrics:
    tags:
      application: ${spring.application.name} # prometheus label 에 추가됨
    export:
      prometheus:
        enabled: true